/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupAdminRouteImport } from './routes/setup-admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register.index'
import { Route as TicketCodeRouteImport } from './routes/ticket.$code'
import { Route as RegisterGuestRouteImport } from './routes/register.guest'
import { Route as RegisterFybRouteImport } from './routes/register.fyb'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const SetupAdminRoute = SetupAdminRouteImport.update({
  id: '/setup-admin',
  path: '/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketCodeRoute = TicketCodeRouteImport.update({
  id: '/ticket/$code',
  path: '/ticket/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterGuestRoute = RegisterGuestRouteImport.update({
  id: '/register/guest',
  path: '/register/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterFybRoute = RegisterFybRouteImport.update({
  id: '/register/fyb',
  path: '/register/fyb',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/setup-admin': typeof SetupAdminRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/register/fyb': typeof RegisterFybRoute
  '/register/guest': typeof RegisterGuestRoute
  '/ticket/$code': typeof TicketCodeRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/setup-admin': typeof SetupAdminRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/register/fyb': typeof RegisterFybRoute
  '/register/guest': typeof RegisterGuestRoute
  '/ticket/$code': typeof TicketCodeRoute
  '/register': typeof RegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/setup-admin': typeof SetupAdminRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/register/fyb': typeof RegisterFybRoute
  '/register/guest': typeof RegisterGuestRoute
  '/ticket/$code': typeof TicketCodeRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/setup-admin'
    | '/admin'
    | '/register/fyb'
    | '/register/guest'
    | '/ticket/$code'
    | '/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/setup-admin'
    | '/admin'
    | '/register/fyb'
    | '/register/guest'
    | '/ticket/$code'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/setup-admin'
    | '/_authenticated/admin'
    | '/register/fyb'
    | '/register/guest'
    | '/ticket/$code'
    | '/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SetupAdminRoute: typeof SetupAdminRoute
  RegisterFybRoute: typeof RegisterFybRoute
  RegisterGuestRoute: typeof RegisterGuestRoute
  TicketCodeRoute: typeof TicketCodeRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup-admin': {
      id: '/setup-admin'
      path: '/setup-admin'
      fullPath: '/setup-admin'
      preLoaderRoute: typeof SetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$code': {
      id: '/ticket/$code'
      path: '/ticket/$code'
      fullPath: '/ticket/$code'
      preLoaderRoute: typeof TicketCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/guest': {
      id: '/register/guest'
      path: '/register/guest'
      fullPath: '/register/guest'
      preLoaderRoute: typeof RegisterGuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/fyb': {
      id: '/register/fyb'
      path: '/register/fyb'
      fullPath: '/register/fyb'
      preLoaderRoute: typeof RegisterFybRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SetupAdminRoute: SetupAdminRoute,
  RegisterFybRoute: RegisterFybRoute,
  RegisterGuestRoute: RegisterGuestRoute,
  TicketCodeRoute: TicketCodeRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
